# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user_name', models.CharField(max_length=100)),
                ('user_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('tag_line', models.CharField(max_length=100)),
                ('entries_per_page', models.IntegerField(default=10)),
                ('recents', models.IntegerField(default=5)),
                ('recent_comments', models.IntegerField(default=5)),
            ],
            options={
                'ordering': ['title'],
            },
            managers=[
                ('default', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('text', models.TextField()),
                ('summary', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('published_date', models.DateTimeField(null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('is_comments_allowed', models.BooleanField(default=True)),
                ('meta_keywords', models.TextField(blank=True, null=True)),
                ('meta_descriptions', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_date'],
                'verbose_name_plural': 'Blog entries',
            },
            managers=[
                ('default', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('basecomment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.BaseComment')),
                ('is_spam', models.BooleanField(default=False)),
                ('is_public', models.NullBooleanField()),
                ('user_agent', models.CharField(default='', max_length=200)),
            ],
            bases=('blog.basecomment',),
            managers=[
                ('default', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='basecomment',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Entry'),
        ),
    ]
