# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 04:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160404_0739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-created_date'], 'permissions': (('view_entry', 'Can see available entry'), ('edit_entry', 'Can update the entry'), ('close_entry', 'Can remove the entry')), 'verbose_name_plural': 'Blog entries'},
        ),
    ]
