# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 01:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160406_0417'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-created_date'], 'verbose_name_plural': 'Blog entries'},
        ),
    ]
